---
- name: Install basic packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - software-properties-common
    - curl
    - apt-transport-https
    - ca-certificates

- name: Get Docker GPG key
  shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    update_cache: yes

- name: Install Docker
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - docker-ce
    - docker-compose

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: true

- name: Add user to Docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
