---
- hosts: all

  vars:
    appdir: "/home/vagrant/spring"
    branch: "main"

  pre_tasks:
      - name: Install Java
        apt:
            name: openjdk-21-jdk
            state: present
            update_cache: yes
        become: yes

      - name: Install Maven
        become: yes
        apt:
          name: maven
          state: present

  tasks:
      - name: "Clone the Spring repository"
        git:
            repo: "https://github.com/Spotinum/localDocAppBackend.git"
            dest: "{{ appdir }}"
            version: "{{ branch }}"
            force: yes

      - name: "Populate application.properties"
        lineinfile:
          dest: "{{ appdir }}/src/main/resources/application.properties"
          state: present
          regexp: "^{{item.key}}="
          line: "{{item.key}}={{item.value}}"
        with_items:
          - "{{app.env | dict2items}}"


      - name: Build the Spring application
        become: yes
        command: mvn package -Dmaven.test.skip
        args:
          chdir: "{{ appdir }}"


     # - name: "Build the Spring application"
      #  command: "./mvnw package -Dmaven.test.skip "
       # args:
        #    chdir: "{{ appdir }}/localDocWebApp"
       # become: yes



      - name: copy spring service file
        template:
          src: ../files/spring.service.j2
          dest: "/etc/systemd/system/spring.service"
        become: yes
        become_user: root
        notify: restart spring

      - name: ensure spring service started
        service:
          name: spring
          state: started
          enabled: yes
        become: yes

      - name: "APT - install nginx"
        apt:
          name: nginx
          update_cache: yes
        become: yes

      - name: copy nginx conf file
        template:
          src: ../files/nginx.http.j2
          dest: "/etc/nginx/sites-available/spring"
        become: yes

      - name: enable spring site in nginx
        file:
          src: "/etc/nginx/sites-available/spring"
          dest: "/etc/nginx/sites-enabled/spring"
          state: link
        become: yes
        notify: restart nginx

      - name: de-activate default nginx site
        file:
          path: /etc/nginx/sites-enabled/default
          state: absent
        become: yes
        notify: restart nginx


  handlers:
  - name: restart spring
    service:
      name: spring
      state: restarted
    become: yes

  - name: restart nginx
    service:
      name: nginx
      state: restarted
    become: yes
